#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x63D7264C05687D7E (animtim@gmail.com)
#
Name     : gcompris-qt
Version  : 0.91
Release  : 1
URL      : http://gcompris.net/download/qt/src/gcompris-qt-0.91.tar.xz
Source0  : http://gcompris.net/download/qt/src/gcompris-qt-0.91.tar.xz
Source99 : http://gcompris.net/download/qt/src/gcompris-qt-0.91.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0 LAL-1.2 MPL-2.0
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : git
BuildRequires : kdoctools-dev
BuildRequires : mesa-dev
BuildRequires : pkgconfig(Qt5Multimedia)
BuildRequires : pkgconfig(Qt5Qml)
BuildRequires : pkgconfig(Qt5Sensors)
BuildRequires : pkgconfig(Qt5Svg)
BuildRequires : pkgconfig(Qt5UiTools)
BuildRequires : pkgconfig(Qt5XmlPatterns)
BuildRequires : qttools-extras

%description
GCompris / I Got IT
GCompris is a GNU package
http://gcompris.net
GCompris is a high quality educational software suite, including a large
number of activities for children aged 2 to 10. Some of the activities
are game orientated, but nonetheless still educational.

%prep
%setup -q -n gcompris-qt-0.91

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535153110
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535153110
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/gcompris-qt
cp COPYING %{buildroot}/usr/share/doc/gcompris-qt/COPYING
cp src/activities/checkers/LICENSE %{buildroot}/usr/share/doc/gcompris-qt/src_activities_checkers_LICENSE
cp src/core/COPYING %{buildroot}/usr/share/doc/gcompris-qt/src_core_COPYING
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
